# Mapeamento de Consoles para as chaves de assets do Discord
DISCORD_CONSOLE_ASSETS = {
    'Arcade': 'arc',
    'Atari 2600': '2600',
    '32X': '32x',
    '3DO Interactive Multiplayer': '3do',
    'Atari 5200': '5200',
    'Atari 7800': '7800',
    'IBM PC 8088': '8088',
    'NEC PC-9800': '9800',
    'Apple II': 'a2',
    'Commodore Amiga': 'amiga',
    'Commodore 64': 'c64',
    'Philips CD-i': 'cd-i',
    'CHIP-8': 'chip-8',
    'Amstrad CPC': 'cpc',
    'ColecoVision': 'cv',
    'Dreamcast': 'dc',
    'DEC Mate': 'decmate',
    'MS-DOS': 'dos',
    'Nintendo DS': 'ds',
    'Nintendo DSi': 'dsi',
    'Famicom Disk System': 'fds',
    'FM Towns': 'fm-towns',
    'Game & Watch': 'g&w',
    'Game Boy': 'gb',
    'Game Boy Advance': 'gba',
    'Game Boy Color': 'gbc',
    'GameCube': 'gc',
    'Game Gear': 'gg',
    'Intellivision': 'intv',
    'Atari Jaguar': 'jag',
    'Atari Lynx': 'lynx',
    'Genesis/Mega Drive': 'md',
    'MSX': 'msx',
    'Nokia N-Gage': 'n-gage',
    'Nintendo 64': 'n64',
    'NES/Famicom': 'nes',
    'Neo Geo CD': 'ngcd',
    'Neo Geo Pocket': 'ngp',
    'PC-FX': 'pc-fx',
    'NEC PC Engine': 'pce',
    'PICO-8': 'pico-8',
    'Sega Pico': 'pico',
    'PlayStation': 'ps1',
    'PlayStation 2': 'ps2',
    'PlayStation 3': 'ps3',
    'PlayStation Portable': 'psp',
    'Saturn': 'sat',
    'Sega CD': 'scd',
    'Master System': 'sms',
    'SNES/Super Famicom': 'snes',
    'TI-83': 'ti-83',
    'TIC-80': 'tic-80',
    'Wii': 'wii',
    'Wii U': 'wiiu',
    'WonderSwan': 'ws',
    'Xbox': 'xbox',
    'ZX81': 'zx81',
    'ZX Spectrum': 'zxs'
}